spring.application.name=apik8s
spring.datasource.url=jdbc:postgresql://localhost:5432/apik8s
spring.datasource.username=postgres
spring.datasource.password=K1g@mboni
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
#server.port=9999