spring.application.name=FrontEndApi
server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5433/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver
